-- Q1 Retrieve the total number of rentals made in the Sakila database.--
select count(rental_id) from rental;

    
    
-- Q2 Find the average rental duration (in days) of movies rented from the Sakila database.
select avg (datediff (return_date, rental_date)) as AverageRentalDuration from rental;



-- Q3. Display the first name and last name of customers in uppercase.
select upper(first_name) as FirstName, upper( last_name) as LastName from customer;

-- Q4. Extract the month from the rental date and display it alongside the rental ID.
select rental_id, month(rental_date) as RentalMonth from rental;




-- Q5. Retrieve the count of rentals for each customer (display customer ID and the count of rentals).
select customer_id, count(rental_id) from rental group by customer_id ;

-- Q6. Find the total revenue generated by each store.
select store.store_id, sum(amount) as total
 from store 
 left join staff on store.store_id left join payment on staff.staff_id 
 group by store.store_id;

-- Q7.Display the title of the movie, customer s first name, and last name who rented it.
select film.title as MovieTitle,
    customer.first_name as CustomerFirstName,
    customer.last_name as CustomerLastName
from 
    rental
join
    inventory on rental.inventory_id = inventory.inventory_id
join
    film on inventory.film_id = film.film_id
join 
    customer on rental.customer_id = customer.customer_id;
    
    
    
    
-- Q8. Retrieve the names of all actors who have appeared in the film "Gone with the Wind. 
select actor.first_name as actor_name
 from actor
 join 
 film_actor on actor.actor_id = film_actor.actor_id
 join
 film 
 on film_actor.film_id= film.film_id
 where film.title like "Gone with the Wind";      -- no film with g 
 
 -- Q9. Determine the total number of rentals for each category of movies. 
select  film_category.category_id,
Count(*) as Rental_Count
from film_category
join 
film
on  film_category.film_id = film.film_id
join
inventory 
on film_category.film_id= inventory.film_id
join
rental
on 
inventory.inventory_id= rental.inventory_id
group by 
    film_category.category_id;
    
    
    
    
-- Q10. -- Find the average rental rate of movies in each language. 
select language.name as Language,
    avg(film.rental_rate) as Average_Rental_Rate
from 
    film
join
    language 
    on film.language_id = language.language_id
group by
    language.name;
    


-- Q11. Retrieve the customer names along with the total amount they've spent on rentals.    
select customer.customer_id,
    customer.first_name,
    customer.last_name,
Sum(payment.amount) as total
from
customer
join 
payment on customer.customer_id = payment.customer_id
group by 
customer.customer_id, customer.first_name, customer.last_name;




-- Q12. List the titles of movies rented by each customer in a particular city (e.g., 'London'). 
Select
    customer.customer_id,
    customer.first_name,
    customer.last_name,
    city.city,
    film.title as MovieTitle
    from
    customer
join 
    address on customer.address_id = address.address_id
join
    city on address.city_id = city.city_id
join
    rental on customer.customer_id = rental.customer_id
join
    inventory on rental.inventory_id = inventory.inventory_id
join
    film on inventory.film_id = film.film_id
where
    city.city = 'London'
order by 
    customer.customer_id, film.title, city.city;




-- Q13.  Display the top 5 rented movies along with the number of times they've been rented. 
Select
    film.title as MovieTitle,
    count(rental.rental_id) as RentalCount
from 
    film
join
    inventory on film.film_id = inventory.film_id
join
    rental on inventory.inventory_id = rental.inventory_id
group by 
    film.title
order by
    RentalCount desc
limit 5;





-- Q14. Determine the customers who have rented movies from both stores (store ID 1 and store ID 2). 

Select 
    customer.customer_id,
    customer.first_name,
    customer.last_name
from 
    customer
join
    rental on customer.customer_id = rental.customer_id
join
    inventory on rental.inventory_id = inventory.inventory_id
join
    store on inventory.store_id = store.store_id
where
    store.store_id in (1, 2)
group by 
    customer.customer_id, customer.first_name, customer.last_name
having
    COUNT(distinct store.store_id) = 2;